# Spring Boot configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_demo
    username: springdemo
    password: springdemo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 4096KB
      max-request-size: 5120KB

# Server configuration
server:
 port: 8180

# Spring Security configuration
# Kui on application.properties fail:
# security.oauth2.client.clientId = 936494890557-26a1ruat2hp65ha20be49mij49eglcem.apps.googleusercontent.com
# security.oauth2.client.clientSecret = Gl6M2svLKPnot7RACYqUQQFi
security:
  oauth2:
    client:
      clientId: 936494890557-26a1ruat2hp65ha20be49mij49eglcem.apps.googleusercontent.com
      clientSecret: Gl6M2svLKPnot7RACYqUQQFi
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true